# Generated by Django 6.0.7 on 2026-07-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='author/')),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Author Profile',
                'verbose_name_plural': 'Author Profile',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imprint_name', models.CharField(default='The Living Word Library', max_length=120)),
                ('tagline', models.CharField(default='Scripture for Life. Wisdom for Generations.', max_length=200)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/')),
                ('intro_text', models.TextField(default="The Living Word Library is a family of devotional books rooted in personal encounter with God through Scripture — written to help you know Him more deeply and walk in the potential He's placed in you.", help_text='Shown under the hero headline on the homepage.')),
                ('mission_text', models.TextField(default="Each book in this library stands on its own, yet they share one heart: to help readers encounter truth, not just study it. Whether you're seeking the names of God, the wisdom of His voice, or the lives that echo His faithfulness through Scripture, there's a book here for this season of your walk.", help_text="Shown in the 'One heart. Many entry points.' section.")),
                ('footer_blurb', models.CharField(default='Devotional books rooted in Scripture — written to help you encounter God, not just study Him.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
