# Generated by Django 6.0.7 on 2026-07-22 00:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('author_name', models.CharField(blank=True, default='', help_text="Display name on the book page. Leave blank to use the site's Author Profile name.", max_length=150)),
                ('short_description', models.CharField(help_text='One line shown on the homepage and books grid cards.', max_length=160)),
                ('description', models.TextField(help_text="Full description shown on the book's own page.")),
                ('whats_inside', models.TextField(blank=True, help_text="'What you'll find inside' section on the book page.")),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('sample_excerpt', models.FileField(blank=True, help_text='Optional sample chapter/excerpt (PDF/EPUB) offered on the book page.', upload_to='samples/')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='0–100. Applied to price while discount_active_until is in the future.')),
                ('discount_active_until', models.DateTimeField(blank=True, help_text='Discount stops applying automatically after this date.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('restricted', 'Restricted')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Amazon, Apple Books, Barnes & Noble', max_length=80)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_links', to='books.book')),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
    ]
