# Generated by Django 5.2.17 on 2026-08-17 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_store_url',
            field=models.URLField(blank=True, default='', help_text='Optional outbound Amazon listing URL shown on the book detail page.', verbose_name='Amazon store URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_file',
            field=models.FileField(blank=True, help_text='Full paid ebook file. Accepts PDF or EPUB. Keep this file protected in production.', upload_to='ebooks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub'])]),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='', help_text='Optional ISBN-10 or ISBN-13 identifier.', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100. Applied to price while discount_active_until is in the future.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='sample_excerpt',
            field=models.FileField(blank=True, help_text='Optional public sample chapter/excerpt. Accepts PDF or EPUB.', upload_to='samples/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub'])]),
        ),
    ]
