# Generated by Django 5.2.17 on 2026-08-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_amazon_store_url_book_ebook_file_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, help_text="Automatically generated QR code for this book's public detail page.", upload_to='qr_codes/'),
        ),
    ]
